import time
import requests
import ccxt
import pandas as pd
import ta

# ================= تنظیمات ربات تلگرام =================
# توکن ربات تلگرام و Chat ID خود را اینجا وارد کنید
TELEGRAM_BOT_TOKEN = "7963493206:AAH5Z_z_your_actual_token"  # توکن خود را چک کنید
TELEGRAM_CHAT_ID = "6175027599"  # آیدی عددی تلگرام شما

# لیست ۲۰ جفت‌ارز اصلی بازار
SYMBOLS = [
    'BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'BNB/USDT', 'XRP/USDT',
        'ADA/USDT', 'AVAX/USDT', 'DOGE/USDT', 'DOT/USDT', 'LINK/USDT',
            'NEAR/USDT', 'LTC/USDT', 'SHIB/USDT', 'SUI/USDT', 'PEPE/USDT',
                'APT/USDT', 'FET/USDT', 'RENDER/USDT', 'TON/USDT', 'TRX/USDT'
                ]

                TIMEFRAME = '15m'  # تایم‌فریم تحلیل (۱۵ دقیقه)
                CHECK_INTERVAL_SECONDS = 300  # بررسی هر ۵ دقیقه یک‌بار

                # اتصال به صرافی (بدون نیاز به تحریم و کلید API برای دیتای عمومی)
                exchange = ccxt.coinex({'enableRateLimit': True})

                def send_telegram_message(message: str):
                    """ارسال پیام به تلگرام"""
                        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
                            payload = {
                                    "chat_id": TELEGRAM_CHAT_ID,
                                            "text": message,
                                                    "parse_mode": "HTML"
                                                        }
                                                            try:
                                                                    res = requests.post(url, json=payload, timeout=10)
                                                                            return res.json()
                                                                                except Exception as e:
                                                                                        print(f"Error sending telegram msg: {e}")

                                                                                        def fetch_data(symbol, timeframe='15m', limit=100):
                                                                                            """دریافت کندل‌ها و محاسبه اندیکاتورها"""
                                                                                                try:
                                                                                                        bars = exchange.fetch_ohlcv(symbol, timeframe=timeframe, limit=limit)
                                                                                                                df = pd.DataFrame(bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
                                                                                                                        
                                                                                                                                # محاسبه اندیکاتورها
                                                                                                                                        df['rsi'] = ta.momentum.RSIIndicator(df['close'], window=14).rsi()
                                                                                                                                                df['ema_20'] = ta.trend.EMAIndicator(df['close'], window=20).ema_indicator()
                                                                                                                                                        df['ema_50'] = ta.trend.EMAIndicator(df['close'], window=50).ema_indicator()
                                                                                                                                                                
                                                                                                                                                                        macd = ta.trend.MACD(df['close'])
                                                                                                                                                                                df['macd_line'] = macd.macd()
                                                                                                                                                                                        df['macd_signal'] = macd.macd_signal()
                                                                                                                                                                                                df['macd_diff'] = macd.macd_diff()
                                                                                                                                                                                                        
                                                                                                                                                                                                                return df
                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                            print(f"Error fetching data for {symbol}: {e}")
                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                    def analyze_market():
                                                                                                                                                                                                                                        """اسکن ۲۰ ارز و صدور سیگنال دقیق"""
                                                                                                                                                                                                                                            print(f"--- Scanning {len(SYMBOLS)} markets at {time.strftime('%Y-%m-%d %H:%M:%S')} ---")
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    for symbol in SYMBOLS:
                                                                                                                                                                                                                                                            df = fetch_data(symbol, timeframe=TIMEFRAME)
                                                                                                                                                                                                                                                                    if df is None or len(df) < 50:
                                                                                                                                                                                                                                                                                continue
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                last = df.iloc[-1]
                                                                                                                                                                                                                                                                                                        prev = df.iloc[-2]
                                                                                                                                                                                                                                                                                                                price = last['close']
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                # شرایط سیگنال خرید (LONG)
                                                                                                                                                                                                                                                                                                                                        long_condition = (
                                                                                                                                                                                                                                                                                                                                                    (last['rsi'] < 38) and 
                                                                                                                                                                                                                                                                                                                                                                (last['close'] > last['ema_20']) and 
                                                                                                                                                                                                                                                                                                                                                                            (prev['macd_diff'] <= 0 and last['macd_diff'] > 0)
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                    # شرایط سیگنال فروش (SHORT)
                                                                                                                                                                                                                                                                                                                                                                                                            short_condition = (
                                                                                                                                                                                                                                                                                                                                                                                                                        (last['rsi'] > 62) and 
                                                                                                                                                                                                                                                                                                                                                                                                                                    (last['close'] < last['ema_20']) and 
                                                                                                                                                                                                                                                                                                                                                                                                                                                (prev['macd_diff'] >= 0 and last['macd_diff'] < 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if long_condition:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sl = round(price * 0.985, 4)  # استاپ لاس ۱.۵ درصد پایین‌تر
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tp1 = round(price * 1.02, 4)   # تارگت اول ۲ درصد
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tp2 = round(price * 1.04, 4)   # تارگت دوم ۴ درصد
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    msg = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"🟢 <b>سیگنال معامله لانگ (خرید)</b>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"━━━━━━━━━━━━━━━━━━\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"🪙 <b>ارز:</b> <code>{symbol}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"⏱ <b>تایم‌فریم:</b> {TIMEFRAME}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"💵 <b>نقطه ورود:</b> <code>{price}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"🎯 <b>تارگت اول (TP1):</b> <code>{tp1}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"🎯 <b>تارگت دوم (TP2):</b> <code>{tp2}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"⛔️ <b>حد ضرر (SL):</b> <code>{sl}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"📊 <b>شاخص RSI:</b> {round(last['rsi'], 1)}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"━━━━━━━━━━━━━━━━━━\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"⚠️ <i>مدیریت سرمایه و ریسک فراموش نشود.</i>"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"[SIGNAL LONG] {symbol}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        send_telegram_message(msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif short_condition:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sl = round(price * 1.015, 4)  # استاپ ۱.۵ درصد بالاتر
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tp1 = round(price * 0.98, 4)   # تارگت اول ۲ درصد
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tp2 = round(price * 0.96, 4)   # تارگت دوم ۴ درصد
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        msg = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"🔴 <b>سیگنال معامله شورت (فروش)</b>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"━━━━━━━━━━━━━━━━━━\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"🪙 <b>ارز:</b> <code>{symbol}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"⏱ <b>تایم‌فریم:</b> {TIMEFRAME}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"💵 <b>نقطه ورود:</b> <code>{price}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"🎯 <b>تارگت اول (TP1):</b> <code>{tp1}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"🎯 <b>تارگت دوم (TP2):</b> <code>{tp2}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"⛔️ <b>حد ضرر (SL):</b> <code>{sl}</code>\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"📊 <b>شاخص RSI:</b> {round(last['rsi'], 1)}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"━━━━━━━━━━━━━━━━━━\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"⚠️ <i>مدیریت سرمایه و ریسک فراموش نشود.</i>"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"[SIGNAL SHORT] {symbol}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            send_telegram_message(msg)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                send_telegram_message("🚀 <b>ربات اسکنر ۲۴ ساعته ترید فعال شد!</b>\nپایش ۲۰ ارز برتر آغاز گردید.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Bot is successfully started and scanning...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # حلقه بی‌پایان برای اجرای ۲۴ ساعته
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    analyze_market()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Error in execution loop: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # وقفه ۵ دقیقه‌ای تا کندل بعدی
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                time.sleep(CHECK_INTERVAL_SECONDS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                